@startuml object

object Member {
}

rectangle Github {
    object GithubAccount {
        userName
        mailAddress
        orgId
        teamId
    }
}

object UserName
UserName : userName

object MailAddress 
MailAddress : mailAddress

object TeamId
TeamId : teamId

object OrgId
OrgId : orgId

Member <|-- GithubAccount
GithubAccount o-- UserName
GithubAccount o-- MailAddress
GithubAccount o-- TeamId
GithubAccount o-- OrgId

@enduml